Repository StamIot/HandyMirror-E-commerce-Client, pull requests merged in 2023-06, with the labels that each got.

#4 Feature: create three controllers
  src/Controller/AboutController.php
  src/Controller/ContactController.php
  src/Controller/FAQController.php
  src/Controller/LegalNotitesController.php
  templates/about/index.html.twig
  templates/contact/index.html.twig
  templates/faq/index.html.twig
  templates/legal_notites/index.html.twig
Labels: enhancement

#3 Feature: create about controller
  src/Controller/AboutController.php
  templates/about/index.html.twig
Labels: enhancement

#5 feature/createStructure
  src/Controller/AboutController.php
  src/Controller/FAQController.php
  src/Controller/HomeController.php
  templates/about/index.html.twig
  templates/base.html.twig
  templates/default/index.html.twig
  templates/home/index.html.twig
  templates/legal_notites/index.html.twig
Labels: enhancement

#9 Feature: add sass
  .gitignore
  assets/app.js
  assets/bootstrap.js
  assets/controllers.json
  assets/controllers/hello_controller.js
  assets/styles/app.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/webpack_encore.yaml
  package-lock.json
  package.json
  public/images/outils.jpg
  src/Controller/AboutController.php
  src/Controller/ContactController.php
  src/Controller/FAQController.php
  src/Controller/HomeController.php
  src/Controller/LegalNotitesController.php
  symfony.lock
  templates/about/index.html.twig
  templates/base.html.twig
  templates/contact/index.html.twig
  templates/faq/index.html.twig
  templates/home/describe_product.html.twig
  templates/home/index.html.twig
  templates/legal_notites/index.html.twig
  webpack.config.js
Labels: enhancement

#6 feature: add describe product
  public/images/outils.jpg
  templates/home/describe_product.html.twig
  templates/home/index.html.twig
Labels: enhancement

#10 feature: add content about file
  templates/about/index.html.twig
Labels: enhancement

#16 Feature/signup
  .env
  composer.json
  composer.lock
  config/routes.yaml
  src/Controller/MailController.php
  templates/email/sent.html.twig
Labels: enhancement

#17 Feature/signup
  .env
  composer.json
  composer.lock
  config/packages/security.yaml
  config/routes.yaml
  config/services.yaml
  migrations/Version20230622133829.php
  package-lock.json
  src/Controller/AccountConfirmationController.php
  src/Controller/RegistrationController.php
  src/Entity/User.php
Labels: enhancement

#21 Hotfix/entity project
  src/Entity/Product.php
  src/Repository/ProductRepository.php
Labels: duplicate

#20 feature: Product
  src/Entity/Product.php
  src/Repository/ProductRepository.php
Labels: enhancement

#22 Feature: create signup controller
  assets/app.js
  assets/styles/app.scss
  config/packages/twig.yaml
  migrations/Version20230626132021.php
  migrations/Version20230626140542.php
  package-lock.json
  package.json
  src/Controller/SignupController.php
  src/Entity/User.php
  src/Form/SignupType.php
  templates/signup/index.html.twig
Labels: enhancement

#19 feature: test databse
  migrations/Version20230626132021.php
Labels: enhancement

#23 feature: stucture sass
  assets/styles/app.scss
  assets/styles/base/_reset.scss
  assets/styles/base/_typography.scss
  assets/styles/components/_buttons.scss
  assets/styles/components/_form.scss
  assets/styles/components/_navbar.scss
  assets/styles/layout/_footer.scss
  assets/styles/layout/_grid.scss
  assets/styles/layout/_header.scss
  assets/styles/layout/_layout.scss
  assets/styles/pages/_about.scss
  assets/styles/pages/_cart.scss
  assets/styles/pages/_confirmation.scss
  assets/styles/pages/_contact.scss
  assets/styles/pages/_faq.scss
  assets/styles/pages/_home.scss
  assets/styles/pages/_legalNotice.scss
  assets/styles/pages/_login.scss
  assets/styles/pages/_payment.scss
  assets/styles/pages/_productDetail.scss
  assets/styles/pages/_productList.scss
  assets/styles/pages/_register.scss
  assets/styles/utils/_functions.scss
  assets/styles/utils/_mixins.scss
  assets/styles/utils/_variables.scss
Labels: enhancement

#24 Update/signin
  .DS_Store
  migrations/Version20230627091349.php
  src/Controller/SignupController.php
  src/Entity/Product.php
  src/Entity/User.php
Labels: enhancement

#27 feature: create a service
  public/logs/handyLogs.log
  src/Controller/HomeController.php
  src/Service/HandyLogs.php
Labels: enhancement

#28 update: signup
  public/logs/handyLogs.log
  src/Controller/SignupController.php
Labels: enhancement

#29 feature: create mixin
  assets/styles/utils/_mixins.scss
Labels: enhancement

#31 update: navbar
  assets/styles/components/_navbar.scss
  assets/styles/layout/_header.scss
  src/Controller/LogInController.php
  templates/base.html.twig
  templates/layout/header.html.twig
Labels: enhancement

#32 feature: add easy admin
  .DS_Store
  assets/bootstrap.js
  composer.json
  composer.lock
  config/bundles.php
  config/packages/uid.yaml
  package.json
  src/Controller/Admin/DashboardController.php
  src/Controller/Admin/ProductCrudController.php
  src/Controller/Admin/UserCrudController.php
  src/Controller/SignupController.php
  symfony.lock
  templates/admin/connect-to-my-dashboard.html.twig
  templates/admin/panel-admin.html.twig
  templates/layout/header.html.twig
  webpack.config.js
Labels: enhancement

#33 update:Signup
  src/Form/SignupType.php
Labels: enhancement

#34 update: easy admin
  package-lock.json
Labels: bug

#40 patch: SignUp
  public/logs/handyLogs.log
  src/Controller/SignupController.php
  templates/signup/index.html.twig
Labels: bug

#42 Feature/forgotpassword
  .env
  composer.json
  composer.lock
  config/bundles.php
  config/packages/reset_password.yaml
  migrations/Version20230629135606.php
  migrations/Version20230629140125.php
  src/Controller/ResetPasswordController.php
  src/Controller/SecurityController.php
  src/Entity/ResetPasswordRequest.php
  src/Form/ChangePasswordFormType.php
  src/Form/LogInFormType.php
  src/Form/ResetPasswordRequestFormType.php
  src/Repository/ResetPasswordRequestRepository.php
  symfony.lock
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/security/login.html.twig
  templates/security/login_form.html.twig
Labels: enhancement

#43 Patch: code review
  .gitignore
  src/Controller/SignupController.php
  src/Form/SignupType.php
  templates/signup/index.html.twig
Labels: patch

#44 patch: code review Login
  config/packages/framework.yaml
  config/packages/security.yaml
  package-lock.json
  src/Controller/SecurityController.php
  src/Security/LogInFormAuthenticator.php
  templates/login/login.html.twig
Labels: patch

#45 Feature/about team
  assets/styles/app.css
  config/packages/doctrine.yaml
  migrations/Version20230630072104.php
  public/images/linkedin/linkedin.png
  public/images/team/Zeinab.jpeg
  public/images/team/alain.jpeg
  public/images/team/sophie.jpeg
  public/images/team/tarek.jpeg
  src/Controller/Admin/DashboardController.php
  templates/about/index.html.twig
Labels: enhancement

#46 Feature/add notification
  assets/styles/app.css
  composer.json
  composer.lock
  config/bundles.php
  config/packages/flasher.yaml
  config/packages/flasher_toastr.yaml
  public/vendor/flasher/flasher-toastr.min.css
  public/vendor/flasher/flasher-toastr.min.js
  public/vendor/flasher/flasher.min.css
  public/vendor/flasher/flasher.min.js
  public/vendor/flasher/jquery.min.js
  src/Controller/SignupController.php
  symfony.lock
Labels: enhancement

#49 Update/ForgotPassword
  .DS_Store
  .env
  composer.json
  composer.lock
  config/routes.yaml
  config/services.yaml
  src/Controller/MailController.php
  src/Controller/RegistrationController.php
  src/Controller/ResetPasswordController.php
  templates/reset_password/email.html.twig
Labels: enhancement
