Repository StamIot/HandyMirror-E-commerce-Client, pull requests merged in 2023-07, with the labels that each got.

#52 feature: add style about
  assets/styles/app.scss
  assets/styles/layout/_header.scss
  assets/styles/layout/_layout.scss
  assets/styles/pages/_about.scss
  assets/styles/pages/_home.scss
  assets/styles/utils/_mixins.scss
  assets/styles/utils/_variables.scss
  templates/about/index.html.twig
  templates/base.html.twig
Labels: enhancement

#63 feature: dashboard
  public/images/team/.DS_Store
  src/Controller/AccountController.php
  src/Controller/SecurityController.php
Labels: enhancement

#65 feature: structure update
  .DS_Store
  assets/styles/layout/_footer.scss
  assets/styles/pages/_home.scss
  public/.DS_Store
  public/images/.DS_Store
  public/images/greenit.jpg
  public/images/mirroir.jpg
  public/images/objectifs.jpg
  templates/home/index.html.twig
Labels: enhancement

#68 feature: update strucutre
  assets/styles/layout/_layout.scss
  templates/base.html.twig
Labels: enhancement

#71 feature: Create CategoryCrudController
  src/Controller/Admin/CategoryCrudController.php
  src/Controller/Admin/DashboardController.php
Labels: enhancement

#77 update:add thumbnail
  migrations/Version20230704075745.php
  src/Entity/Product.php
Labels: update

#78 update: entity adress
  migrations/Version20230704093409.php
  src/Entity/Address.php
Labels: update

#79 update: page product
  src/Controller/ProductsListController.php
  templates/products_list/index.html.twig
Labels: update

#81 Update/headernavbar
  src/Controller/ProductController.php
  templates/layout/header.html.twig
  templates/product/index.html.twig
Labels: update

#80 feature: product by id
  src/Controller/ProductController.php
  templates/product/index.html.twig
Labels: enhancement

#82 update/changeuser
  .DS_Store
  assets/styles/app.scss
  assets/styles/pages/_changeUser.scss
  config/routes.yaml
  config/services.yaml
  src/Controller/UserChangeController.php
  src/Entity/Address.php
  src/Entity/User.php
  src/Form/AddressType.php
  src/Form/UserChangeType.php
  templates/security/login.html.twig
  templates/user_change/index.html.twig
Labels: enhancement

#84 update/useraccount
  assets/styles/pages/_account.scss
  src/Controller/AccountController.php
  src/Controller/EditPasswordController.php
  templates/account/index.html.twig
  templates/edit_password/index.html.twig
  templates/user_change/index.html.twig
Labels: enhancement

#85 hotfix: fix category
  migrations/Version20230704181821.php
  public/images/thumbnails/Mirror1.jpg
  public/images/thumbnails/miroir.webp
  public/upload/products/miroir-a62bd3f6a3ee80c017708e146c9ddffa565dafd2.webp
  public/upload/products/mirror1-1d1b5e4d609dd224c920b921937c7f172047436a.jpg
  src/Controller/Admin/ProductCrudController.php
  src/Controller/ProductController.php
  src/Entity/Category.php
  src/Entity/Product.php
  templates/product/index.html.twig
  templates/products_list/index.html.twig
Labels: enhancement, patch, update

#86 hotfix:img
  public/images/mirroir.jpg
Labels: bug fixed

#87 feature: Cart bug
  src/Classes/ShoppingCart.php
  src/Controller/CartController.php
Labels: bug

#89 test: update title
  assets/styles/components/_navbar.scss
  templates/layout/header.html.twig
  templates/reset_password/request.html.twig
Labels: enhancement

#88 feature: add img for dashboard
  public/images/thumbnails/400d0d0cf2e5153441b0032847f64f72843bac91.jpg
  public/images/thumbnails/55db3803ef2d59b28cc747555a830f2635dc5e65.webp
  public/images/thumbnails/572fbacd151c43298c7cb1c435d70f3ad80e1e8e.jpg
  public/images/thumbnails/93598726e07a79a0540e2fc3ba3a8d568efa2f8f.jpg
  public/images/thumbnails/a84f21c00a615b360f76429a3105efa171594a8f.png
  public/images/thumbnails/b9a1c015c8493379558d1c94f65fab8a42f1c91c.jpg
  public/images/thumbnails/df8bb64ba3a2775ff6a7bad11fb4021bd26edb25.jpg
  public/upload/products/05-07-2023-chiffon-specs-572fbacd151c43298c7cb1c435d70f3ad80e1e8e.jpg
  public/upload/products/05-07-2023-chiffons-a84f21c00a615b360f76429a3105efa171594a8f.png
  public/upload/products/05-07-2023-chiffons-format-93598726e07a79a0540e2fc3ba3a8d568efa2f8f.jpg
  public/upload/products/05-07-2023-encadre-df8bb64ba3a2775ff6a7bad11fb4021bd26edb25.jpg
  public/upload/products/05-07-2023-magic-mirror-xxl-400d0d0cf2e5153441b0032847f64f72843bac91.jpg
  public/upload/products/05-07-2023-miroir-xl-b9a1c015c8493379558d1c94f65fab8a42f1c91c.jpg
  public/upload/products/05-07-2023-spray-55db3803ef2d59b28cc747555a830f2635dc5e65.webp
Labels: enhancement, update

#91 patch:AccountController
  src/Controller/AccountController.php
Labels: update

#92 patch: controller
  src/Controller/AccountController.php
  templates/account/index.html.twig
Labels: patch

#93 Patch/signup controller
  src/Controller/SignupController.php
Labels: update

#94 patch: form
  src/Form/UserChangeType.php
  templates/user_change/index.html.twig
Labels: bug, update

#95 feature: patch style edit account
  assets/styles/pages/_account.scss
  src/Controller/AccountController.php
  templates/account/index.html.twig
Labels: enhancement

#100 feature: create a cart session
  config/packages/framework.yaml
  src/Classes/ShoppingCart.php
  src/Controller/CartController.php
  templates/cart/index.html.twig
  templates/product/index.html.twig
Labels: enhancement

#101 feature: create cart style
  assets/styles/pages/_cart.scss
  assets/styles/utils/_utils.scss
  src/Controller/UserChangeController.php
  templates/cart/index.html.twig
Labels: enhancement

#102 feature: add btn clear
  assets/styles/pages/_cart.scss
  templates/cart/index.html.twig
Labels: enhancement

#103 feature: add data to cart
  assets/styles/pages/_cart.scss
  src/Classes/ShoppingCart.php
  src/Controller/CartController.php
  templates/cart/index.html.twig
Labels: enhancement

#104 Feature: code review
  assets/styles/app.scss
  assets/styles/components/_navbar.scss
  assets/styles/layout/_layout.scss
  assets/styles/pages/_account.scss
  assets/styles/pages/_changeUser.scss
  assets/styles/pages/_productDetail.scss
  assets/styles/pages/_productList.scss
  public/images/icon1.png
  public/images/icon2.png
  public/images/icon3.png
  public/images/icon4.png
  public/images/icon5.png
  public/images/icon6.png
  public/images/icon7.png
  src/Classes/ShoppingCart.php
  src/Controller/AboutController.php
  src/Controller/AccountController.php
  src/Controller/Admin/DashboardController.php
  src/Controller/CartController.php
  templates/account/index.html.twig
  templates/layout/header.html.twig
  templates/product/index.html.twig
  templates/products_list/index.html.twig
Labels: enhancement

#105 feature: code review Cart
  assets/styles/components/_buttons.scss
  assets/styles/components/_form.scss
  assets/styles/pages/_cart.scss
  public/images/icons/user/icon1.png
  public/images/icons/user/icon2.png
  public/images/icons/user/icon3.png
  public/images/icons/user/icon4.png
  public/images/icons/user/icon5.png
  public/images/icons/user/icon6.png
  public/images/icons/user/icon7.png
  src/Classes/ShoppingCart.php
  src/Controller/CartController.php
  src/Entity/Product.php
  templates/cart/index.html.twig
  templates/product/index.html.twig
Labels: enhancement

#107 patch:login
  composer.lock
  public/images/thumbnails/a12e33d009c637492e1e5ff081a0a054ffde8490.jpg
  public/upload/products/08-07-2023-magic-a12e33d009c637492e1e5ff081a0a054ffde8490.jpg
  src/Controller/SecurityController.php
Labels: bug fixed

#108 patch: account
  src/Controller/AccountController.php
  src/Controller/SecurityController.php
Labels: bug fixed
